/**
 * Bundles the Manja stylesheet.
 *
 * Lightning CSS resolves the relative @imports and downlevels modern syntax to
 * the browser baseline. This script owns the cascade-layer ordering, which has
 * to be the very first statement in the file to take effect.
 */
import { createRequire } from 'node:module';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundle, transform } from 'lightningcss';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, 'src');
const DIST = path.join(here, 'dist');

/**
 * Declaring the order up front means a component stylesheet can be imported at
 * any point and still land in the right place. Anything the consuming app
 * writes is unlayered, and unlayered styles beat every layer — so apps override
 * us without specificity hacks.
 */
const LAYER_ORDER = '@layer mj.tokens, mj.reset, mj.base, mj.components, mj.utilities;';

/** `major.minor.patch` packed the way Lightning CSS expects. */
const v = (major, minor = 0, patch = 0) => (major << 16) | (minor << 8) | patch;

/** Baseline is set by `@layer` support: Safari 15.4, Chrome 99, Firefox 97. */
const targets = {
  chrome: v(105),
  edge: v(105),
  firefox: v(110),
  safari: v(15, 4),
};

const banner = `/**
 * Manja Design System — stylesheet.
 * Auto-generated by packages/styles/build.mjs. Do not edit by hand.
 */`;

function compile(filename) {
  const { code } = bundle({ filename, targets, minify: false });
  return code.toString();
}

function minify(code, filename) {
  const result = transform({
    filename,
    code: Buffer.from(code),
    targets,
    minify: true,
  });
  return result.code.toString();
}

async function main() {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  // Tokens are inlined so that `@manja/styles` is a single self-contained
  // stylesheet — one import gets an app a themed, reset baseline.
  const tokensCss = await readFile(require.resolve('@manja/tokens/css'), 'utf8');
  const tokensLayer = [
    '@layer mj.tokens {',
    tokensCss
      .split('\n')
      .map((line) => (line.trim() ? `  ${line}` : line))
      .join('\n')
      .trimEnd(),
    '}',
  ].join('\n');

  const full = [banner, LAYER_ORDER, tokensLayer, compile(path.join(SRC, 'index.css'))]
    .join('\n\n')
    .trimEnd();

  await writeFile(path.join(DIST, 'manja.css'), `${full}\n`);
  await writeFile(path.join(DIST, 'manja.min.css'), `${minify(full, 'manja.css')}\n`);

  // Granular entry points, for apps that already own their reset or that want
  // the tokens without any of our opinions.
  const parts = ['reset', 'base', 'utilities'];
  for (const part of parts) {
    const code = [banner, LAYER_ORDER, compile(path.join(SRC, `${part}.css`))]
      .join('\n\n')
      .trimEnd();
    await writeFile(path.join(DIST, `${part}.css`), `${code}\n`);
  }

  /**
   * TypeScript 6 rejects a side-effect import of a module it has no
   * declaration for, so `import '@manja/styles'` would fail to typecheck in
   * every consuming app. Shipping this stub fixes it once, for everyone.
   */
  await writeFile(
    path.join(DIST, 'manja.d.ts'),
    [
      '/**',
      ' * `@manja/styles` is a stylesheet, not a module. This declaration exists so',
      " * that `import '@manja/styles'` typechecks; the import has no runtime exports.",
      ' */',
      'export {};',
      '',
    ].join('\n'),
  );

  const bytes = Buffer.byteLength(full);
  const minBytes = Buffer.byteLength(minify(full, 'manja.css'));
  console.log(
    `styles: manja.css ${(bytes / 1024).toFixed(1)}kB, minified ${(minBytes / 1024).toFixed(1)}kB, ` +
      `${parts.length} granular entry points`,
  );
}

main().catch((error) => {
  console.error(`\nstyles build failed:\n${error.message}\n`);
  process.exitCode = 1;
});
